name: Update nixpkgs and packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

concurrency:
  group: update
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: nixos/nix-installer-action@main
        
      - name: Configure Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""
          flakehub-api-server: ""
          flakehub-cache-server: ""
          use-flakehub: false
          use-gha-cache: true

      - name: Update nixpkgs flake input
        run: |
          nix flake update nixpkgs

      - name: Run package update scripts
        run: |
          pkgs/osu-lazer-bin/update.sh

      - name: Run flake checks
        run: |
          nix flake check

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ci: update nixpkgs and packages"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
